### ISSUE TITLE
can't read the property "loaded" of underfined

### ISSUE THREAD

**Issue by damamsrinivas** [makeomatic/redux-connect#40] opened 2016-06-25 15:04 UTC
I'm using redux with immutable js.

```
TypeError: Cannot read property 'loaded' of undefined
[1]     at AsyncConnect.isLoaded (/node_modules/redux-connect/lib/components/AsyncConnect.js:67:59)
```

**Comment by AVVS** [comment] 2016-06-25 15:05
I havent used it with immutable.js and there is a request for this already https://github.com/makeomatic/redux-connect/issues/15

However, it looks like you dont have reducer enabled and prop is not passed from state?

**Comment by damamsrinivas** [comment] 2016-06-25 15:26
When I console log the store I have reduxAsyncConnect state in it as below.

`{ reduxAsyncConnect: { loaded: true, loadState: {} },
`

**Comment by AVVS** [comment] 2016-06-25 15:29
https://github.com/makeomatic/redux-connect/blob/master/modules/components/AsyncConnect.js#L58-L60

`this.context.store.getState().reduxAsyncConnect.loaded ` must be defined. I guess immutable js provides different semantics for accessing props of store

**Comment by AVVS** [comment] 2016-06-25 15:29
And part `.reduxAsyncConnect` must be changed somehow

**Comment by AVVS** [comment] 2016-06-28 10:17
closing as duplicate of #15

**Closed by AVVS** 2016-06-28 10:17 UTC
Labels: question
