### ISSUE TITLE
When using deferred = true, asyncConnect is not working

### ISSUE THREAD

**Issue by idangozlan** [makeomatic/redux-connect#98] opened 2016-12-20 22:54 UTC
Hi,

It's known issue? when turning `deferred: true`, the asyncConnect not being triggered

Any suggestions?

**Comment by AVVS** [comment] 2016-12-20 23:23
Duplicate of https://github.com/makeomatic/redux-connect/issues/30

**Closed by AVVS** 2016-12-20 23:23 UTC
